language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
sudo: false
branches:
  only:
    master
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
before_script:
  - python api.py &
  - sleep 5 # give server time to start
script:
  - cd tests
  - python run.py
