language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
sudo: false
branches:
  only: master
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
before_script:
  - python api.py &
  - sleep 5 # give server time to start
script:
  - cd tests
  - python run.py
notifications:
  slack:
    secure: UHlfGKmX/yC/eAtSHBxF9iUaGXWKSP+Xe2GD5/0fPoS85iYmenVWxKS04PgovBz9ttYnPVbHdTkr+UO+b3EJsJHSPi/L8upt7Hryz4YqAXUPxFaUG1FSPm1fuLfB4Yq451knkuohxPJQt6CqxcqumvD8zlREKmdKwEY5MhOamGFsCtVD+B1Ob4YzYH1YRmV3D1zdH8ykvnZLEOawcw9n9+/XrSE0/6TL2EQORxiHnEe9fcjCuuFqZP+Qyo7LrjWSQZy2dcHzPnwfgwMyID9flpeIjzWig8pDPx/zffoib5zIEyGjQxxgbE4lt3vibykWqVmXcXYS6+OegykmbFuRGxkKSISEx7Peji58zsLy9V/tGouYDg0ksYnypB12haVnufdTClTXStSU05M+Mdlb8CF47dGMmvtFnIn74r41KB/Ah9sWEC9iCh/0bwVhsJNlfIRv3KlgLp4EOn5KIRTJNDvEYbm/9L0vKUwKN6gWdcu4vO26vdEvUn6uOtvY92oPoXVYydeDiYQ0iF0VomE9ThvM9G0FPV4AgyEbwMxuWSTYODyZoJlrsHAjku1znwxrbIsAGXTgZRLj+atdzAmTS7C7wI2AL0kwyBHJT2PkPje+pIUVv5JnvY7QW/C/j4lZYtx7ktmfxYNmWJMRWqhuYJenGvRm0gc3osR4Zj1zw3w=
    on_success: change
    on_failure: change
