---
- hosts: all
  tasks:
  - name: write the apache config file
    template: src=deploy/chemnitz-sensorAPI.conf.j2 dest=/etc/apache2/sites-available/chemnitz-sensorAPI.conf
    notify:
      - reload apache

  - git: repo=https://github.com/codeforchemnitz/SensorAPI.git dest=/srv/chemnitz-sensorapi
    notify:
      - touch wsgi

  - stat: path=/srv/chemnitz-sensorapi/.virtualenv
    register: virtualenv

  - shell: virtualenv -p python2 .virtualenv
    args:
      chdir: /srv/chemnitz-sensorapi
    when: virtualenv.stat.exists == False

  - pip: requirements=/srv/chemnitz-sensorapi/requirements.txt virtualenv=/srv/chemnitz-sensorapi/.virtualenv

  - stat: path=/etc/apache2/sites-enabled/chemnitz-sensorAPI.conf
    register: apache2site

  - shell: a2ensite chemnitz-sensorAPI
    when: apache2site.stat.exists == False

  handlers:
    - name: reload apache
      service: name=apache2 state=reloaded

    - name: touch wsgi
      shell: touch /srv/chemnitz-sensorapi/deploy/wsgi.py
